dist: trusty
sudo: required
language: node_js
node_js:
  - "6.9.5"
os:
  - linux
services:
  - docker
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

before_script:
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - ng test --watch=false --code-coverage
#  - (npm start > /dev/null &) && (npm run e2e)
  - docker-compose up -d
  - docker-compose ps
  - docker-compose exec npm run lint
  - docker-compose exec npm run ng-build-prod
  - npm run e2e -- --baseUrl="http://localhost:9090/"
  - docker-compose down

after_success:
  - bash <(curl -s https://codecov.io/bash)
#  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
#  - docker push headcult/angular2starter:dev

deploy:
  provider: heroku
  api_key:
    secure: "46d1d6da-8ea5-4ac2-98ad-a09b39295587"
  on: dev
  app: angular2starter-dev
