dist: trusty
sudo: required
language: node_js
node_js:
  - "6"
os:
  - linux
services:
  - docker
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser

before_script:
  - sh -e /etc/init.d/xvfb start

before_install:
  - docker build -t angular2starter-nodejs .
  - docker run -it -d --name angular2starter -p 9090:8080 headcult/angular2starter-nodejs:initial
  - docker ps -a

install:
  - npm install

script:
  - ng lint
  - ng build
  - ng test --watch=false --code-coverage
  - (npm start > /dev/null &) && (npm run e2e)
  - docker ps -a
  - npm run e2e -- --baseUrl="http://localhost:9090/"

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker tag angular2starter-nodejs:latest headcult/angular2starter-nodejs:initial
  - docker ps -a

deploy:
  provider: heroku
  api_key:
    secure: "46d1d6da-8ea5-4ac2-98ad-a09b39295587"
  on: upgrades
  app: angular2starter-headcult
