dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
services:
  - docker
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start

before_install:
- docker build -t angular2starter-nodejs .
- docker run -it -d --name angular2starter -p 3001:8080 angular2starter-nodejs
- docker ps -a

install:
  - npm install
script:
  - ng lint
  - ng build
  - ng test --watch false --code-coverage

after_success:
  - bash <(curl -s https://codecov.io/bash)
