dist: trusty
sudo: required
language: node_js
node_js:
  - "5"
os:
  - linux
env:
  global:
    - DBUS_SESSION_BUS_ADDRESS=/dev/null
    - DISPLAY=:99.0
    - CHROME_BIN=chromium-browser
before_script:
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
  - ng lint
  - ng build
  - ng test --watch=false --code-coverage
  - (npm start > /dev/null &) && (npm run e2e)

after_success:
  - bash <(curl -s https://codecov.io/bash)

deploy:
  provider: heroku
  api_key:
    secure: "46d1d6da-8ea5-4ac2-98ad-a09b39295587"
  on: upgrades
